#cloud-config
apt:
  sources:
    winswitch:
      source: "deb http://winswitch.org/ bionic main"
      keyid: "C11C 0A4D F702 EDF6 C04F 458C 18AD B31C F18A D6BB"
packages:
  - xpra
  - firefox
  - libcanberra-gtk3-module
  - pulseaudio
runcmd:
  - [ systemctl, disable, --now, xpra, snapd, snapd.socket ]
timezone: US/Pacific
