#cloud-config
apt:
  sources:
    winswitch:
      source: "deb http://winswitch.org/ bionic main"
      keyid: "C11C 0A4D F702 EDF6 C04F 458C 18AD B31C F18A D6BB"
packages:
  - xpra
  - pulseaudio
runcmd:
  - [ systemctl, disable, --now, xpra, snapd, snapd.socket ]
#  - [ snap, install, '--classic', slack ]  # Snap version of Slack wasn't working (Snap unit files were not disabled). LXD does support Snap though. See https://stgraber.org/2016/12/07/running-snaps-in-lxd-containers/
  - [ wget, -O, slack-desktop-3.2.1-amd64.deb, 'https://downloads.slack-edge.com/linux_releases/slack-desktop-3.2.1-amd64.deb' ]
  - [ dpkg, --install, slack-desktop-3.2.1-amd64.deb ]
  - [ rm, -f, slack-desktop-3.2.1-amd64.deb ]
  - [ apt, --yes, --fix-broken, install ]  # install dependencies that dpkg missed
timezone: US/Pacific
