#cloud-config
#
# https://typora.io/#linux
apt:
  conf: |
    Unattended-Upgrade {
      Allowed-Origins {
        "${distro_id}:${distro_codename}-updates";
        "${distro_id}:${distro_codename}-backports";
        "winswitch.org:bionic";
        "typora.io:";
      };
    };
    APT {
      Periodic {
        Download-Upgradeable-Packages "1";
      };
    };
  sources:
    winswitch:
      source: "deb http://winswitch.org/ bionic main"
      keyid: "C11C 0A4D F702 EDF6 C04F 458C 18AD B31C F18A D6BB"
    typora:
      source: "deb https://typora.io/linux ./"
      keyid: "4AC4 41BE 68B4 ADAB 7439  FBF9 BA30 0B77 55AF CFAE"
packages:
  - xpra
  - typora
  - libgtk-3-0
  - libxss1
runcmd:
  - [ systemctl, disable, --now, xpra, snapd, snapd.socket ]
timezone: US/Pacific
